spring:
  cloud:
    gcp:
      trace:
        enabled: false
      logging:
        enabled: false
  application:
    name: transaction_service
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    initialisation-mode: always
    pool:
      enabled: true
      initial-size: 5
      max-idle-time: 1m
      max-size: 5
      max-create-connection-time: 10s
      max-acquire-time: 10s
    url: r2dbc:postgresql://localhost:5432/transactions
    username: root
    password: password
  liquibase:
    change-log: liquibase/changelog-master.yaml
    url: jdbc:postgresql://localhost:5432/transactions
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
  datasource:
    hikari:
      connection-timeout: 10_000 # 10 sec
  thymeleaf:
    reactive:
      max-chunk-size: 8192
  jackson:
    deserialization:
      fail-on-unknown-properties: false